markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Cyber Coffee
tagline:          "Insights from Liam O'Connell"
baseurl:          /

author:
  name:           Long

paginate:         5
recent-num:       5
article_num:      5
